# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'INetSimAnalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_INetSimAnalyzer(object):
    def setupUi(self, INetSimAnalyzer):
        INetSimAnalyzer.setObjectName("INetSimAnalyzer")
        INetSimAnalyzer.resize(1861, 1245)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(INetSimAnalyzer)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_leftSide = QtWidgets.QVBoxLayout()
        self.verticalLayout_leftSide.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_leftSide.setSpacing(2)
        self.verticalLayout_leftSide.setObjectName("verticalLayout_leftSide")
        self.groupBox_General = QtWidgets.QGroupBox(INetSimAnalyzer)
        self.groupBox_General.setObjectName("groupBox_General")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_General)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_Start = QtWidgets.QPushButton(self.groupBox_General)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.verticalLayout_5.addWidget(self.pushButton_Start)
        self.pushButton_Config = QtWidgets.QPushButton(self.groupBox_General)
        self.pushButton_Config.setObjectName("pushButton_Config")
        self.verticalLayout_5.addWidget(self.pushButton_Config)
        self.pushButton_Stop = QtWidgets.QPushButton(self.groupBox_General)
        self.pushButton_Stop.setEnabled(False)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.verticalLayout_5.addWidget(self.pushButton_Stop)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_General)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textEdit_DebugOutput = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_DebugOutput.setMaximumSize(QtCore.QSize(16777215, 130))
        self.textEdit_DebugOutput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_DebugOutput.setObjectName("textEdit_DebugOutput")
        self.verticalLayout_7.addWidget(self.textEdit_DebugOutput)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.graphicsView_Alarm = QtWidgets.QGraphicsView(self.groupBox_General)
        self.graphicsView_Alarm.setMinimumSize(QtCore.QSize(80, 80))
        self.graphicsView_Alarm.setMaximumSize(QtCore.QSize(80, 80))
        self.graphicsView_Alarm.setStyleSheet("background-color: transparent;\n"
"border-radius: 40px;\n"
"border: 2px;\n"
"border-style: solid;\n"
"border-color: black;")
        self.graphicsView_Alarm.setObjectName("graphicsView_Alarm")
        self.horizontalLayout_5.addWidget(self.graphicsView_Alarm)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.pushButton_ResetAlarm = QtWidgets.QPushButton(self.groupBox_General)
        self.pushButton_ResetAlarm.setObjectName("pushButton_ResetAlarm")
        self.gridLayout_2.addWidget(self.pushButton_ResetAlarm, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_WatchMode = QtWidgets.QCheckBox(self.groupBox_General)
        self.checkBox_WatchMode.setObjectName("checkBox_WatchMode")
        self.horizontalLayout_6.addWidget(self.checkBox_WatchMode)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 6)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_PathReport = QtWidgets.QLabel(self.groupBox_General)
        self.label_PathReport.setObjectName("label_PathReport")
        self.gridLayout.addWidget(self.label_PathReport, 3, 0, 1, 1)
        self.label_PathLogs = QtWidgets.QLabel(self.groupBox_General)
        self.label_PathLogs.setObjectName("label_PathLogs")
        self.gridLayout.addWidget(self.label_PathLogs, 2, 0, 1, 1)
        self.lineEdit_PathLogs = QtWidgets.QLineEdit(self.groupBox_General)
        self.lineEdit_PathLogs.setObjectName("lineEdit_PathLogs")
        self.gridLayout.addWidget(self.lineEdit_PathLogs, 2, 1, 1, 1)
        self.pushButton_PathLogs = QtWidgets.QPushButton(self.groupBox_General)
        self.pushButton_PathLogs.setObjectName("pushButton_PathLogs")
        self.gridLayout.addWidget(self.pushButton_PathLogs, 2, 2, 1, 1)
        self.lineEdit_PathReport = QtWidgets.QLineEdit(self.groupBox_General)
        self.lineEdit_PathReport.setObjectName("lineEdit_PathReport")
        self.gridLayout.addWidget(self.lineEdit_PathReport, 3, 1, 1, 1)
        self.pushButton_PathReport = QtWidgets.QPushButton(self.groupBox_General)
        self.pushButton_PathReport.setObjectName("pushButton_PathReport")
        self.gridLayout.addWidget(self.pushButton_PathReport, 3, 2, 1, 1)
        self.pushButton_Refresh = QtWidgets.QPushButton(self.groupBox_General)
        self.pushButton_Refresh.setObjectName("pushButton_Refresh")
        self.gridLayout.addWidget(self.pushButton_Refresh, 4, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_leftSide.addWidget(self.groupBox_General)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_Type = QtWidgets.QGroupBox(INetSimAnalyzer)
        self.groupBox_Type.setEnabled(True)
        self.groupBox_Type.setObjectName("groupBox_Type")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_Type)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_FilterFile = QtWidgets.QGroupBox(self.groupBox_Type)
        self.groupBox_FilterFile.setObjectName("groupBox_FilterFile")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_FilterFile)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboBox_FilterFiles = QtWidgets.QComboBox(self.groupBox_FilterFile)
        self.comboBox_FilterFiles.setObjectName("comboBox_FilterFiles")
        self.verticalLayout_6.addWidget(self.comboBox_FilterFiles)
        self.verticalLayout.addWidget(self.groupBox_FilterFile)
        self.groupBox_FilterTypes = QtWidgets.QGroupBox(self.groupBox_Type)
        self.groupBox_FilterTypes.setObjectName("groupBox_FilterTypes")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_FilterTypes)
        self.verticalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.listView_FilterType = QtWidgets.QListView(self.groupBox_FilterTypes)
        self.listView_FilterType.setProperty("showDropIndicator", False)
        self.listView_FilterType.setAlternatingRowColors(True)
        self.listView_FilterType.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listView_FilterType.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listView_FilterType.setObjectName("listView_FilterType")
        self.verticalLayout_8.addWidget(self.listView_FilterType)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_FilterSelectAll = QtWidgets.QPushButton(self.groupBox_FilterTypes)
        self.pushButton_FilterSelectAll.setObjectName("pushButton_FilterSelectAll")
        self.horizontalLayout_3.addWidget(self.pushButton_FilterSelectAll)
        self.pushButton_FilterSelectNone = QtWidgets.QPushButton(self.groupBox_FilterTypes)
        self.pushButton_FilterSelectNone.setObjectName("pushButton_FilterSelectNone")
        self.horizontalLayout_3.addWidget(self.pushButton_FilterSelectNone)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_FilterTypes)
        self.groupBox_FilterTime = QtWidgets.QGroupBox(self.groupBox_Type)
        self.groupBox_FilterTime.setObjectName("groupBox_FilterTime")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_FilterTime)
        self.verticalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBox_FilterTimeActive = QtWidgets.QCheckBox(self.groupBox_FilterTime)
        self.checkBox_FilterTimeActive.setObjectName("checkBox_FilterTimeActive")
        self.verticalLayout_9.addWidget(self.checkBox_FilterTimeActive)
        self.label_FilterDateTimeStart = QtWidgets.QLabel(self.groupBox_FilterTime)
        self.label_FilterDateTimeStart.setObjectName("label_FilterDateTimeStart")
        self.verticalLayout_9.addWidget(self.label_FilterDateTimeStart)
        self.dateTimeEdit_Start = QtWidgets.QDateTimeEdit(self.groupBox_FilterTime)
        self.dateTimeEdit_Start.setCalendarPopup(False)
        self.dateTimeEdit_Start.setObjectName("dateTimeEdit_Start")
        self.verticalLayout_9.addWidget(self.dateTimeEdit_Start)
        self.label_FilterDateTimeEnd = QtWidgets.QLabel(self.groupBox_FilterTime)
        self.label_FilterDateTimeEnd.setObjectName("label_FilterDateTimeEnd")
        self.verticalLayout_9.addWidget(self.label_FilterDateTimeEnd)
        self.dateTimeEdit_End = QtWidgets.QDateTimeEdit(self.groupBox_FilterTime)
        self.dateTimeEdit_End.setCalendarPopup(False)
        self.dateTimeEdit_End.setObjectName("dateTimeEdit_End")
        self.verticalLayout_9.addWidget(self.dateTimeEdit_End)
        self.verticalLayout.addWidget(self.groupBox_FilterTime)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_Type)
        self.groupBox_Log = QtWidgets.QGroupBox(INetSimAnalyzer)
        self.groupBox_Log.setObjectName("groupBox_Log")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Log)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_ClearLog = QtWidgets.QPushButton(self.groupBox_Log)
        self.pushButton_ClearLog.setObjectName("pushButton_ClearLog")
        self.horizontalLayout_2.addWidget(self.pushButton_ClearLog)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_Search = QtWidgets.QLabel(self.groupBox_Log)
        self.label_Search.setObjectName("label_Search")
        self.horizontalLayout_2.addWidget(self.label_Search)
        self.lineEdit_Search = QtWidgets.QLineEdit(self.groupBox_Log)
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.horizontalLayout_2.addWidget(self.lineEdit_Search)
        self.pushButton_ClearSearch = QtWidgets.QPushButton(self.groupBox_Log)
        self.pushButton_ClearSearch.setObjectName("pushButton_ClearSearch")
        self.horizontalLayout_2.addWidget(self.pushButton_ClearSearch)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableWidget_Computer = QtWidgets.QTableWidget(self.groupBox_Log)
        self.tableWidget_Computer.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget_Computer.setAlternatingRowColors(True)
        self.tableWidget_Computer.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Computer.setObjectName("tableWidget_Computer")
        self.tableWidget_Computer.setColumnCount(5)
        self.tableWidget_Computer.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Computer.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Computer.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Computer.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Computer.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_Computer.setHorizontalHeaderItem(4, item)
        self.tableWidget_Computer.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableWidget_Computer)
        self.horizontalLayout_4.addWidget(self.groupBox_Log)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 8)
        self.verticalLayout_leftSide.addLayout(self.horizontalLayout_4)
        self.verticalLayout_leftSide.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout_leftSide)

        self.retranslateUi(INetSimAnalyzer)
        QtCore.QMetaObject.connectSlotsByName(INetSimAnalyzer)

    def retranslateUi(self, INetSimAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        INetSimAnalyzer.setWindowTitle(_translate("INetSimAnalyzer", "INetSimAnalyzer"))
        self.groupBox_General.setTitle(_translate("INetSimAnalyzer", "General"))
        self.pushButton_Start.setText(_translate("INetSimAnalyzer", "Start INetSim"))
        self.pushButton_Config.setText(_translate("INetSimAnalyzer", "Edit Config"))
        self.pushButton_Stop.setText(_translate("INetSimAnalyzer", "Stop INetSim"))
        self.groupBox.setTitle(_translate("INetSimAnalyzer", "INetSim Output:"))
        self.pushButton_ResetAlarm.setText(_translate("INetSimAnalyzer", "Reset Alarm"))
        self.checkBox_WatchMode.setText(_translate("INetSimAnalyzer", "Activate Watch Mode"))
        self.label_PathReport.setText(_translate("INetSimAnalyzer", "Report Path:"))
        self.label_PathLogs.setText(_translate("INetSimAnalyzer", "Log Path:"))
        self.lineEdit_PathLogs.setText(_translate("INetSimAnalyzer", "/var/log/inetsim"))
        self.pushButton_PathLogs.setText(_translate("INetSimAnalyzer", "Browse"))
        self.lineEdit_PathReport.setText(_translate("INetSimAnalyzer", "/var/log/inetsim/report"))
        self.pushButton_PathReport.setText(_translate("INetSimAnalyzer", "Browse"))
        self.pushButton_Refresh.setText(_translate("INetSimAnalyzer", "Refresh"))
        self.groupBox_Type.setTitle(_translate("INetSimAnalyzer", "Filter"))
        self.groupBox_FilterFile.setTitle(_translate("INetSimAnalyzer", "File:"))
        self.groupBox_FilterTypes.setTitle(_translate("INetSimAnalyzer", "Types:"))
        self.pushButton_FilterSelectAll.setText(_translate("INetSimAnalyzer", "Select All"))
        self.pushButton_FilterSelectNone.setText(_translate("INetSimAnalyzer", "Unselect All"))
        self.groupBox_FilterTime.setTitle(_translate("INetSimAnalyzer", "Time:"))
        self.checkBox_FilterTimeActive.setText(_translate("INetSimAnalyzer", "Activate"))
        self.label_FilterDateTimeStart.setText(_translate("INetSimAnalyzer", "DateTime Start:"))
        self.dateTimeEdit_Start.setDisplayFormat(_translate("INetSimAnalyzer", "yyyy-MM-dd HH:mm:ss"))
        self.label_FilterDateTimeEnd.setText(_translate("INetSimAnalyzer", "DateTime End:"))
        self.dateTimeEdit_End.setDisplayFormat(_translate("INetSimAnalyzer", "yyyy-MM-dd HH:mm:ss"))
        self.groupBox_Log.setTitle(_translate("INetSimAnalyzer", "Log"))
        self.pushButton_ClearLog.setText(_translate("INetSimAnalyzer", "Clear Log"))
        self.label_Search.setText(_translate("INetSimAnalyzer", "Search:"))
        self.pushButton_ClearSearch.setText(_translate("INetSimAnalyzer", "Clear Search"))
        self.tableWidget_Computer.setSortingEnabled(True)
        item = self.tableWidget_Computer.horizontalHeaderItem(0)
        item.setText(_translate("INetSimAnalyzer", "Timestamp"))
        item = self.tableWidget_Computer.horizontalHeaderItem(1)
        item.setText(_translate("INetSimAnalyzer", "Session"))
        item = self.tableWidget_Computer.horizontalHeaderItem(2)
        item.setText(_translate("INetSimAnalyzer", "Type"))
        item = self.tableWidget_Computer.horizontalHeaderItem(3)
        item.setText(_translate("INetSimAnalyzer", "IP"))
        item = self.tableWidget_Computer.horizontalHeaderItem(4)
        item.setText(_translate("INetSimAnalyzer", "Info"))

